name: Generate Coq for Cryptol Prelude
on:
  push:
    branches: [vr/coq-of-cryptol-prelude master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    branches: [vr/coq-of-cryptol-prelude master]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ghc: ["8.10.2"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: coq-of-cryptol-prelude - ${{ matrix.os }} - GHC ${{ matrix.ghc }}
    continue-on-error: [false]
    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-haskell@v1
        id: setup-haskell
        with:
          ghc-version: ${{ matrix.ghc }}

      - name: Cache cabal store
        uses: actions/cache@v2
        with:
          path: |
            ${{ steps.setup-haskell.outputs.cabal-store }}
            dist-newstyle
          key: cabal-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles(format('cabal.GHC-{0}.config', matrix.ghc)) }}-${{ github.sha }}
          restore-keys: |
            cabal-${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles(format('cabal.GHC-{0}.config', matrix.ghc)) }}-

      - name: Build coq-of-cryptol-prelude
        shell: bash
        run: cabal build coq-of-cryptol-prelude

      - name: Run coq-of-cryptol-prelude
        shell: bash
        run: coq-of-cryptol-prelude

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
