name: Type-check handwritten and generated Coq files

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # coq-bits does not support coq >= 8.13 yet
        coq:
          - 8.12.2
          - 8.11.2
          - 8.10.2
        coq-bits-version:
          - 1.0.0
        os:
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    name: saw-core-coq - ${{ matrix.os }} - coq-${{ matrix.coq }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # NOTE: this action is marked as experimental by their author, but it is
      # much faster than avsm@setup-ocaml@v1.  However, if this one ever becomes
      # problematic, it should suffice to switch back to that version.
      - name: Set up ocaml and opam
        uses: ocaml/setup-ocaml@v2
        with:
          # coq-bits claims to support < 4.10 only
          ocaml-compiler: 4.09.x

      - name: Install coq
        run: opam depext --install coq=${{ matrix.coq }}

      - name: Add coq-released repository
        run: opam repo add coq-released https://coq.inria.fr/opam/released

      - name: Install coq-bits
        run: opam depext --install coq-bits=${{ matrix.coq-bits-version }}

      - name: Build saw-core-coq/coq
        working-directory: saw-core-coq/coq
        run: |
          opam exec -- coq_makefile -f _CoqProject -o Makefile.coq
          opam exec -- make
